"""phase_artifacts_and_github_connection

Revision ID: 5c630784a07e
Revises: 63611878199e
Create Date: 2026-09-04 19:04:05.429397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c630784a07e'
down_revision: Union[str, None] = '63611878199e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=False),
    sa.Column('github_login', sa.String(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_github_connection')
    )
    op.create_index(op.f('ix_github_connections_tenant_id'), 'github_connections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=False)
    op.add_column('sessions', sa.Column('idea_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('plan_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('build_depth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'build_depth')
    op.drop_column('sessions', 'plan_confirmed_at')
    op.drop_column('sessions', 'idea_confirmed_at')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_index(op.f('ix_github_connections_tenant_id'), table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
